version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/demo
    volumes:
      - ./app:/usr/src/app
    networks:
      - webnet

  mongo:
    image: mongo:4.4.6
    volumes:
      - mongodata:/data/db
    networks:
      - webnet

volumes:
  mongodata:

networks:
  webnet: